import { Resource, AppInsightsConfig } from '../../types/resources';
import { safeTfName, safeName } from './utils';

export function generateAppInsightsTf(resource: Resource): string {
  const config = resource.config as AppInsightsConfig;
  const tfn = safeTfName(resource.name);
  const sn = safeName(resource.name);

  return `# App Insights + Log Analytics Workspace: ${resource.name}
# Generated by InfraHelper

resource "azurerm_log_analytics_workspace" "${tfn}_law" {
  name                = "\${var.project_name}-\${var.environment}-law-${sn}"
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = "PerGB2018"
  retention_in_days   = ${config.retentionDays}
  tags                = local.tags
}

resource "azurerm_application_insights" "${tfn}" {
  name                = "\${var.project_name}-\${var.environment}-ai-${sn}"
  resource_group_name = var.resource_group_name
  location            = var.location
  workspace_id        = azurerm_log_analytics_workspace.${tfn}_law.id
  application_type    = "${config.kind}"
  retention_in_days   = ${config.retentionDays}
  tags                = local.tags
}
`;
}
