import { Resource, AppServiceConfig } from '../../types/resources';
import { safeTfName, safeName } from './utils';

interface AppServiceTfOptions {
  enableNetworking: boolean;
  aiTfName?: string;
  planTfName?: string;
}

function isLinuxFramework(framework: string): boolean {
  return framework === 'python' || framework === 'node';
}

function getWindowsAppStack(framework: string, version: string): string {
  const v = version.includes('.') ? version : `${version}.0`;
  switch (framework) {
    case 'dotnet':
      return `    application_stack {
      dotnet_version = "v${v}"
    }`;
    case 'java':
      return `    application_stack {
      java_version        = "${version}"
      java_server         = "JAVA"
      java_server_version = "SE"
    }`;
    case 'php':
      return `    application_stack {
      php_version = "${version}"
    }`;
    default:
      return `    application_stack {
      dotnet_version = "v${v}"
    }`;
  }
}

function getLinuxAppStack(framework: string, version: string): string {
  switch (framework) {
    case 'dotnet':
      return `    application_stack {
      dotnet_version = "${version}.0"
    }`;
    case 'node':
      return `    application_stack {
      node_version = "${version}-lts"
    }`;
    case 'python':
      return `    application_stack {
      python_version = "${version}"
    }`;
    case 'java':
      return `    application_stack {
      java_server         = "JAVA"
      java_server_version = "${version}"
    }`;
    case 'php':
      return `    application_stack {
      php_version = "${version}"
    }`;
    default:
      return '';
  }
}

export function generateAppServiceTf(resource: Resource, options: AppServiceTfOptions): string {
  const config = resource.config as AppServiceConfig;
  const tfn = safeTfName(resource.name);
  const sn = safeName(resource.name);

  const isLinux = isLinuxFramework(config.framework);
  const usePrivateEndpoint = options.enableNetworking && config.enablePrivateEndpoint;
  const resourceType = isLinux ? 'azurerm_linux_web_app' : 'azurerm_windows_web_app';

  const dedicatedPlanBlock = !options.planTfName
    ? `
resource "azurerm_service_plan" "${tfn}_plan" {
  name                = "\${var.project_name}-\${var.environment}-asp-${sn}"
  resource_group_name = var.resource_group_name
  location            = var.location
  os_type             = "${isLinux ? 'Linux' : 'Windows'}"
  sku_name            = "${config.sku}"
  tags                = local.tags
}
`
    : '';

  const planIdRef = options.planTfName
    ? `azurerm_service_plan.${options.planTfName}.id`
    : `azurerm_service_plan.${tfn}_plan.id`;

  const aiConnStr = options.aiTfName
    ? `azurerm_application_insights.${options.aiTfName}.connection_string`
    : `""`;

  const customEnvVars = config.envVars
    .map((ev) => `    "${ev.key}" = "${ev.isSecret ? `@Microsoft.KeyVault(SecretUri=<kv-uri>/secrets/${ev.key}/)` : ev.value}"`)
    .join('\n');

  const appSettings = [
    `    "APPLICATIONINSIGHTS_CONNECTION_STRING"   = ${aiConnStr}`,
    `    "ApplicationInsightsAgent_EXTENSION_VERSION" = "~3"`,
    `    "WEBSITE_RUN_FROM_PACKAGE"                = "1"`,
    ...(customEnvVars ? [customEnvVars] : []),
  ].join('\n');

  const vnetIntegration = options.enableNetworking
    ? `
  virtual_network_subnet_id = azurerm_subnet.app_subnet.id`
    : '';

  const applicationStack = isLinux
    ? getLinuxAppStack(config.framework, config.frameworkVersion)
    : getWindowsAppStack(config.framework, config.frameworkVersion);

  const peBlock = usePrivateEndpoint
    ? `
resource "azurerm_private_endpoint" "${tfn}_pe" {
  name                = "\${var.project_name}-\${var.environment}-app-${sn}-pe"
  resource_group_name = var.resource_group_name
  location            = var.location
  subnet_id           = azurerm_subnet.pe_subnet.id

  private_service_connection {
    name                           = "\${var.project_name}-\${var.environment}-app-${sn}-pe-connection"
    private_connection_resource_id = ${resourceType}.${tfn}.id
    subresource_names              = ["sites"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.web.id]
  }
}`
    : '';

  return `# App Service: ${resource.name}
# Generated by InfraHelper
${dedicatedPlanBlock}
resource "${resourceType}" "${tfn}" {
  name                = "\${var.project_name}-\${var.environment}-app-${sn}"
  resource_group_name = var.resource_group_name
  location            = var.location
  service_plan_id     = ${planIdRef}
  https_only          = true${vnetIntegration}

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on         = ${config.enableAlwaysOn}
    ftps_state        = "Disabled"
    minimum_tls_version = "1.2"
    http2_enabled     = true
    health_check_path = "/health"
${applicationStack}
  }

  app_settings = {
${appSettings}
  }

  tags = local.tags
}
${peBlock}
`;
}
