import { Resource, AppServicePlanConfig } from '../../types/resources';
import { safeTfName, safeName } from './utils';

export function generateAspTf(resource: Resource): string {
  const config = resource.config as AppServicePlanConfig;
  const tfn = safeTfName(resource.name);
  const sn = safeName(resource.name);

  return `# App Service Plan: ${resource.name}
# Generated by InfraHelper

resource "azurerm_service_plan" "${tfn}" {
  name                = "\${var.project_name}-\${var.environment}-asp-${sn}"
  resource_group_name = var.resource_group_name
  location            = var.location
  os_type             = "${config.os}"
  sku_name            = "${config.sku}"
  tags                = local.tags
}
`;
}
