import { Resource, KeyVaultConfig } from '../../types/resources';
import { safeTfName, safeName } from './utils';

interface KvTfOptions {
  enableNetworking: boolean;
  diagnosticStorageTfName?: string;
  diagnosticWorkspaceTfName?: string;
}

export function generateKeyVaultTf(resource: Resource, options: KvTfOptions): string {
  const config = resource.config as KeyVaultConfig;
  const tfn = safeTfName(resource.name);
  const sn = safeName(resource.name);

  const usePrivateEndpoint = options.enableNetworking && config.enablePrivateEndpoint;

  const peBlock = usePrivateEndpoint
    ? `
resource "azurerm_private_endpoint" "${tfn}_pe" {
  name                = "\${var.project_name}-\${var.environment}-kv-${sn}-pe"
  resource_group_name = var.resource_group_name
  location            = var.location
  subnet_id           = azurerm_subnet.pe_subnet.id

  private_service_connection {
    name                           = "\${var.project_name}-\${var.environment}-kv-${sn}-pe-connection"
    private_connection_resource_id = azurerm_key_vault.${tfn}.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.keyvault.id]
  }
}`
    : '';

  const hasDiag = !!(options.diagnosticStorageTfName || options.diagnosticWorkspaceTfName);
  const diagStorageLine = options.diagnosticStorageTfName
    ? `  storage_account_id         = azurerm_storage_account.${options.diagnosticStorageTfName}.id`
    : '';
  const diagWorkspaceLine = options.diagnosticWorkspaceTfName
    ? `  log_analytics_workspace_id = azurerm_log_analytics_workspace.${options.diagnosticWorkspaceTfName}_law.id`
    : '';

  const diagBlock = hasDiag
    ? `
resource "azurerm_monitor_diagnostic_setting" "${tfn}_diag" {
  name               = "\${var.project_name}-\${var.environment}-kv-${sn}-diag"
  target_resource_id = azurerm_key_vault.${tfn}.id
${diagStorageLine}
${diagWorkspaceLine}

  enabled_log {
    category = "AuditEvent"
  }

  enabled_log {
    category = "AzurePolicyEvaluationDetails"
  }

  metric {
    category = "AllMetrics"
  }
}`
    : '';

  return `# Key Vault: ${resource.name}
# Generated by InfraHelper

resource "azurerm_key_vault" "${tfn}" {
  # Key Vault names are limited to 24 characters — shorten if needed
  name                = substr("\${var.project_name}-\${var.environment}-kv-${sn}", 0, 24)
  resource_group_name = var.resource_group_name
  location            = var.location
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "${config.sku}"

  enable_rbac_authorization  = true
  soft_delete_retention_days = ${config.softDeleteRetentionDays}
  purge_protection_enabled   = false

  network_acls {
    default_action = "${usePrivateEndpoint ? 'Deny' : 'Allow'}"
    bypass         = ["AzureServices"]
    ip_rules       = []
  }

  tags = local.tags
}
${peBlock}
${diagBlock}
`;
}
