import {
  ProjectConfig,
  FunctionAppConfig,
  AppServiceConfig,
  KeyVaultConfig,
} from '../../types/resources';
import { safeTfName, safeName } from './utils';
import { generateNetworkingTf } from './networkingTf';
import { generateStorageTf } from './storageTf';
import { generateAppInsightsTf } from './appInsightsTf';
import { generateKeyVaultTf } from './keyVaultTf';
import { generateAspTf } from './aspTf';
import { generateFunctionAppTf } from './functionAppTf';
import { generateAppServiceTf } from './appServiceTf';

function generateMainTf(project: ProjectConfig): string {
  const hasKeyVault = project.resources.some((r) => r.type === 'keyVault');

  return `# main.tf — Provider configuration, resource group, and shared locals
# Generated by InfraHelper
# Project: ${project.projectName}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
${hasKeyVault ? '\ndata "azurerm_client_config" "current" {}\n' : ''}
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location
  tags     = local.tags
}

locals {
  tags = {
    environment = var.environment
    project     = var.project_name
    managedBy   = "InfraHelper"
  }
}
`;
}

function generateVariablesTf(project: ProjectConfig): string {
  const needsIpVar = project.resources.some(
    (r) =>
      (r.type === 'functionApp' && (r.config as FunctionAppConfig).allowCurrentIp) ||
      (r.type === 'appService' && (r.config as AppServiceConfig).allowCurrentIp)
  );

  return `# variables.tf — Input variable declarations
# Generated by InfraHelper

variable "project_name" {
  description = "Project name prefix for all resources"
  type        = string
  default     = "${project.projectName}"
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)"
  type        = string
  default     = "${project.environment}"
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be dev, staging, or prod."
  }
}

variable "location" {
  description = "Azure region for all resources"
  type        = string
  default     = "${project.location}"
}

variable "resource_group_name" {
  description = "Name of the Azure resource group"
  type        = string
  default     = "${project.resourceGroupName || `rg-${project.projectName}-${project.environment}`}"
}
${
  needsIpVar
    ? `
variable "allowed_ip_address" {
  description = "IP address allowed through web app access restrictions (your machine IP)"
  type        = string
  default     = "${project.allowedIpAddress || ''}"
}
`
    : ''
}`;
}

function generateOutputsTf(project: ProjectConfig): string {
  const { resources } = project;
  const lines: string[] = [];

  resources
    .filter((r) => r.type === 'storageAccount')
    .forEach((r) => {
      const tfn = safeTfName(r.name);
      lines.push(`output "storage_${tfn}_name" {
  value = azurerm_storage_account.${tfn}.name
}`);
      lines.push(`output "storage_${tfn}_id" {
  value = azurerm_storage_account.${tfn}.id
}`);
    });

  resources
    .filter((r) => r.type === 'appInsights')
    .forEach((r) => {
      const tfn = safeTfName(r.name);
      lines.push(`output "appinsights_${tfn}_connection_string" {
  value     = azurerm_application_insights.${tfn}.connection_string
  sensitive = true
}`);
    });

  resources
    .filter((r) => r.type === 'keyVault')
    .forEach((r) => {
      const tfn = safeTfName(r.name);
      lines.push(`output "keyvault_${tfn}_uri" {
  value = azurerm_key_vault.${tfn}.vault_uri
}`);
    });

  resources
    .filter((r) => r.type === 'functionApp')
    .forEach((r) => {
      const config = r.config as FunctionAppConfig;
      const tfn = safeTfName(r.name);
      const isLinux = config.runtime === 'python' || config.os === 'Linux';
      const rType = isLinux ? 'azurerm_linux_function_app' : 'azurerm_windows_function_app';
      lines.push(`output "functionapp_${tfn}_hostname" {
  value = ${rType}.${tfn}.default_hostname
}`);
      lines.push(`output "functionapp_${tfn}_principal_id" {
  value = ${rType}.${tfn}.identity[0].principal_id
}`);
    });

  resources
    .filter((r) => r.type === 'appService')
    .forEach((r) => {
      const config = r.config as AppServiceConfig;
      const tfn = safeTfName(r.name);
      const isLinux = config.framework === 'python' || config.framework === 'node';
      const rType = isLinux ? 'azurerm_linux_web_app' : 'azurerm_windows_web_app';
      lines.push(`output "appservice_${tfn}_hostname" {
  value = ${rType}.${tfn}.default_hostname
}`);
      lines.push(`output "appservice_${tfn}_principal_id" {
  value = ${rType}.${tfn}.identity[0].principal_id
}`);
    });

  return `# outputs.tf — Resource outputs
# Generated by InfraHelper

${lines.join('\n\n')}
`;
}

function generateRolesTf(project: ProjectConfig): string {
  const { resources } = project;
  const blocks: string[] = [];

  const ROLE_STORAGE_BLOB_OWNER    = 'Storage Blob Data Owner';
  const ROLE_STORAGE_QUEUE_CONTRIB = 'Storage Queue Data Contributor';
  const ROLE_STORAGE_TABLE_CONTRIB = 'Storage Table Data Contributor';
  const ROLE_KV_SECRETS_USER       = 'Key Vault Secrets User';

  // Function App → Storage Account RBAC
  resources.filter((r) => r.type === 'functionApp').forEach((res) => {
    const config = res.config as FunctionAppConfig;
    if (!config.storageAccountRef) return;
    const storageRes = resources.find((r) => r.id === config.storageAccountRef);
    if (!storageRes) return;

    const funcTfn = safeTfName(res.name);
    const saTfn = safeTfName(storageRes.name);
    const isLinux = config.runtime === 'python' || config.os === 'Linux';
    const rType = isLinux ? 'azurerm_linux_function_app' : 'azurerm_windows_function_app';

    const roles = [
      [ROLE_STORAGE_BLOB_OWNER, 'blob_owner'],
      [ROLE_STORAGE_QUEUE_CONTRIB, 'queue_contrib'],
      [ROLE_STORAGE_TABLE_CONTRIB, 'table_contrib'],
    ] as const;

    roles.forEach(([roleName, suffix]) => {
      blocks.push(`# ${roleName}: ${res.name} → ${storageRes.name}
resource "azurerm_role_assignment" "${funcTfn}_${saTfn}_${suffix}" {
  scope                = azurerm_storage_account.${saTfn}.id
  role_definition_name = "${roleName}"
  principal_id         = ${rType}.${funcTfn}.identity[0].principal_id
}`);
    });
  });

  // Key Vault Secrets User: Function Apps and App Services → Key Vault
  resources.filter((r) => r.type === 'keyVault').forEach((kvRes) => {
    const kvConfig = kvRes.config as KeyVaultConfig;
    const kvTfn = safeTfName(kvRes.name);

    kvConfig.accessPolicies.forEach((refId) => {
      const refRes = resources.find((r) => r.id === refId);
      if (!refRes) return;
      const refTfn = safeTfName(refRes.name);

      let principalIdRef = '';
      if (refRes.type === 'functionApp') {
        const cfg = refRes.config as FunctionAppConfig;
        const isLinux = cfg.runtime === 'python' || cfg.os === 'Linux';
        const rType = isLinux ? 'azurerm_linux_function_app' : 'azurerm_windows_function_app';
        principalIdRef = `${rType}.${refTfn}.identity[0].principal_id`;
      } else if (refRes.type === 'appService') {
        const cfg = refRes.config as AppServiceConfig;
        const isLinux = cfg.framework === 'python' || cfg.framework === 'node';
        const rType = isLinux ? 'azurerm_linux_web_app' : 'azurerm_windows_web_app';
        principalIdRef = `${rType}.${refTfn}.identity[0].principal_id`;
      } else {
        return;
      }

      blocks.push(`# ${ROLE_KV_SECRETS_USER}: ${refRes.name} → ${kvRes.name}
resource "azurerm_role_assignment" "${refTfn}_${kvTfn}_kv_secrets_user" {
  scope                = azurerm_key_vault.${kvTfn}.id
  role_definition_name = "${ROLE_KV_SECRETS_USER}"
  principal_id         = ${principalIdRef}
}`);
    });
  });

  if (blocks.length === 0) return '';

  return `# roles.tf — Managed Identity RBAC Role Assignments
# Generated by InfraHelper

${blocks.join('\n\n')}
`;
}

function generateDeployPs1(project: ProjectConfig): string {
  const rg = project.resourceGroupName || `rg-${project.projectName}-${project.environment}`;
  const loc = project.location;
  return `# deploy-terraform.ps1 — Generated by InfraHelper
# Project     : ${project.projectName}
# Run from the root of your repository (the folder containing the terraform/ directory)

param(
  [string]$SubscriptionId = "<YOUR-SUBSCRIPTION-ID>",
  [string]$Environment    = "${project.environment}"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "==> Logging in to Azure..." -ForegroundColor Cyan
az login

Write-Host "==> Setting subscription: \$SubscriptionId" -ForegroundColor Cyan
az account set --subscription \$SubscriptionId

Write-Host "==> Active subscription:" -ForegroundColor Cyan
az account show --query "{name:name, id:id, state:state}" --output table

Write-Host "==> Creating resource group '${rg}' in '${loc}' (if not exists)..." -ForegroundColor Cyan
az group create \`
  --name "${rg}" \`
  --location "${loc}" \`
  --output table

Set-Location terraform

Write-Host "==> Initialising Terraform..." -ForegroundColor Cyan
terraform init

Write-Host "==> Validating configuration..." -ForegroundColor Cyan
terraform validate

Write-Host "==> Planning (environment: \$Environment)..." -ForegroundColor Cyan
terraform plan \`
  -var-file="terraform.\$Environment.tfvars" \`
  -out="tfplan-\$Environment"

Write-Host "==> Applying (environment: \$Environment)..." -ForegroundColor Cyan
terraform apply "tfplan-\$Environment"

Write-Host "==> Deployment complete!" -ForegroundColor Green
Set-Location ..
`;
}

function generateDeploySh(project: ProjectConfig): string {
  const rg = project.resourceGroupName || `rg-${project.projectName}-${project.environment}`;
  const loc = project.location;
  return `#!/usr/bin/env bash
# deploy-terraform.sh — Generated by InfraHelper
# Project     : ${project.projectName}
# Run from the root of your repository (the folder containing the terraform/ directory)

set -euo pipefail

SUBSCRIPTION_ID="\${1:-<YOUR-SUBSCRIPTION-ID>}"
ENVIRONMENT="\${2:-${project.environment}}"
RESOURCE_GROUP="${rg}"
LOCATION="${loc}"

echo "==> Logging in to Azure..."
az login

echo "==> Setting subscription: \$SUBSCRIPTION_ID"
az account set --subscription "\$SUBSCRIPTION_ID"

echo "==> Active subscription:"
az account show --query "{name:name,id:id,state:state}" --output table

echo "==> Creating resource group '\$RESOURCE_GROUP' in '\$LOCATION' (if not exists)..."
az group create \\
  --name "\$RESOURCE_GROUP" \\
  --location "\$LOCATION" \\
  --output table

cd terraform

echo "==> Initialising Terraform..."
terraform init

echo "==> Validating configuration..."
terraform validate

echo "==> Planning (environment: \$ENVIRONMENT)..."
terraform plan \\
  -var-file="terraform.\$ENVIRONMENT.tfvars" \\
  -out="tfplan-\$ENVIRONMENT"

echo "==> Applying (environment: \$ENVIRONMENT)..."
terraform apply "tfplan-\$ENVIRONMENT"

echo "==> Deployment complete!"
cd ..
`;
}

function generateGitHubWorkflowTf(_project: ProjectConfig): string {
  return `name: Deploy Terraform Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.7.0"
  ARM_USE_OIDC: true

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: \${{ inputs.environment || 'dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: \${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        env:
          ARM_CLIENT_ID: \${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: \${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          ENVIRONMENT=\${{ inputs.environment || 'dev' }}
          terraform plan \\
            -var-file="terraform.\${ENVIRONMENT}.tfvars" \\
            -out="tfplan-\${ENVIRONMENT}"

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-\${{ inputs.environment || 'dev' }}
          path: terraform/tfplan-*

  deploy:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: \${{ inputs.environment || 'dev' }}
    concurrency:
      group: tf-deploy-\${{ inputs.environment || 'dev' }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: \${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: \${{ secrets.AZURE_TENANT_ID }}
          subscription-id: \${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: \${{ env.TF_VERSION }}

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-\${{ inputs.environment || 'dev' }}
          path: terraform

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          ARM_CLIENT_ID: \${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: \${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          ENVIRONMENT=\${{ inputs.environment || 'dev' }}
          terraform apply "tfplan-\${ENVIRONMENT}"

      - name: Show outputs
        working-directory: terraform
        env:
          ARM_CLIENT_ID: \${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: \${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: \${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform output
`;
}

function generateTfvars(project: ProjectConfig, env: 'dev' | 'staging' | 'prod'): string {
  const needsIpVar = project.resources.some(
    (r) =>
      (r.type === 'functionApp' && (r.config as FunctionAppConfig).allowCurrentIp) ||
      (r.type === 'appService' && (r.config as AppServiceConfig).allowCurrentIp)
  );

  return `# terraform.${env}.tfvars — Variable values for ${env}
# Generated by InfraHelper
# Usage: terraform apply -var-file="terraform.${env}.tfvars"

project_name        = "${project.projectName}"
environment         = "${env}"
location            = "${project.location}"
resource_group_name = "${project.resourceGroupName || `rg-${project.projectName}-${env}`}"
${needsIpVar ? `allowed_ip_address  = "${project.allowedIpAddress || ''}"` : ''}
`;
}

export function generateTerraformFiles(project: ProjectConfig): Record<string, string> {
  const files: Record<string, string> = {};

  if (project.resources.length === 0) return files;

  const { resources, enableNetworking } = project;
  const byId = new Map(resources.map((r) => [r.id, r]));

  // Core Terraform files
  files['terraform/main.tf'] = generateMainTf(project);
  files['terraform/variables.tf'] = generateVariablesTf(project);
  files['terraform/outputs.tf'] = generateOutputsTf(project);

  // Networking
  if (enableNetworking) {
    files['terraform/networking.tf'] = generateNetworkingTf();
  }

  // Per-resource files
  resources.forEach((resource) => {
    const sn = safeName(resource.name);

    switch (resource.type) {
      case 'storageAccount':
        files[`terraform/storage_${sn}.tf`] = generateStorageTf(resource, { enableNetworking });
        break;

      case 'appInsights':
        files[`terraform/appinsights_${sn}.tf`] = generateAppInsightsTf(resource);
        break;

      case 'keyVault': {
        const config = resource.config as KeyVaultConfig;
        const diagStorageRef = config.diagnosticStorageAccountRef
          ? byId.get(config.diagnosticStorageAccountRef)
          : undefined;
        const diagAiRef = config.diagnosticWorkspaceRef
          ? byId.get(config.diagnosticWorkspaceRef)
          : undefined;
        files[`terraform/keyvault_${sn}.tf`] = generateKeyVaultTf(resource, {
          enableNetworking,
          diagnosticStorageTfName: diagStorageRef ? safeTfName(diagStorageRef.name) : undefined,
          diagnosticWorkspaceTfName: diagAiRef ? safeTfName(diagAiRef.name) : undefined,
        });
        break;
      }

      case 'appServicePlan':
        files[`terraform/asp_${sn}.tf`] = generateAspTf(resource);
        break;

      case 'functionApp': {
        const config = resource.config as FunctionAppConfig;
        const storageRef = config.storageAccountRef ? byId.get(config.storageAccountRef) : undefined;
        const aiRef = config.appInsightsRef ? byId.get(config.appInsightsRef) : undefined;
        const planRef = config.sharedPlanRef ? byId.get(config.sharedPlanRef) : undefined;
        files[`terraform/functionapp_${sn}.tf`] = generateFunctionAppTf(resource, {
          enableNetworking,
          storageTfName: storageRef ? safeTfName(storageRef.name) : undefined,
          aiTfName: aiRef ? safeTfName(aiRef.name) : undefined,
          planTfName: planRef ? safeTfName(planRef.name) : undefined,
        });
        break;
      }

      case 'appService': {
        const config = resource.config as AppServiceConfig;
        const aiRef = config.appInsightsRef ? byId.get(config.appInsightsRef) : undefined;
        const planRef = config.sharedPlanRef ? byId.get(config.sharedPlanRef) : undefined;
        files[`terraform/appservice_${sn}.tf`] = generateAppServiceTf(resource, {
          enableNetworking,
          aiTfName: aiRef ? safeTfName(aiRef.name) : undefined,
          planTfName: planRef ? safeTfName(planRef.name) : undefined,
        });
        break;
      }
    }
  });

  // Role assignments
  const rolesTf = generateRolesTf(project);
  if (rolesTf) {
    files['terraform/roles.tf'] = rolesTf;
  }

  // Per-environment tfvars
  (['dev', 'staging', 'prod'] as const).forEach((env) => {
    files[`terraform/terraform.${env}.tfvars`] = generateTfvars(project, env);
  });

  // Deployment scripts
  files['deploy-terraform.ps1'] = generateDeployPs1(project);
  files['deploy-terraform.sh'] = generateDeploySh(project);
  files['.github/workflows/deploy-terraform.yml'] = generateGitHubWorkflowTf(project);

  return files;
}
