import { Resource, StorageAccountConfig } from '../../types/resources';
import { safeTfName, safeTfStorageName } from './utils';

interface StorageTfOptions {
  enableNetworking: boolean;
}

export function generateStorageTf(resource: Resource, options: StorageTfOptions): string {
  const config = resource.config as StorageAccountConfig;
  const tfn = safeTfName(resource.name);
  const saName = safeTfStorageName(resource.name);

  const skuParts = config.sku.split('_');
  const tier = skuParts[0];
  const replication = skuParts.slice(1).join('_');

  const usePrivateEndpoint = options.enableNetworking && config.enablePrivateEndpoint;

  const containerBlocks = config.containers
    .map(
      (c) => `
resource "azurerm_storage_container" "${tfn}_${safeTfName(c)}" {
  name                  = "${c}"
  storage_account_name  = azurerm_storage_account.${tfn}.name
  container_access_type = ${config.enableBlobPublicAccess ? '"blob"' : '"private"'}
}`
    )
    .join('\n');

  const peBlock = usePrivateEndpoint
    ? `
resource "azurerm_private_endpoint" "${tfn}_pe" {
  name                = "${saName}-pe"
  resource_group_name = var.resource_group_name
  location            = var.location
  subnet_id           = azurerm_subnet.pe_subnet.id

  private_service_connection {
    name                           = "${saName}-pe-connection"
    private_connection_resource_id = azurerm_storage_account.${tfn}.id
    subresource_names              = ["blob"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.blob.id]
  }
}`
    : '';

  return `# Storage Account: ${resource.name}
# Generated by InfraHelper

resource "azurerm_storage_account" "${tfn}" {
  name                     = "${saName}"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "${tier}"
  account_replication_type = "${replication}"
  account_kind             = "${config.kind}"

  min_tls_version                 = "TLS1_2"
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = ${config.enableBlobPublicAccess}
  shared_access_key_enabled       = true

  blob_properties {
    delete_retention_policy {
      days = 7
    }
    container_delete_retention_policy {
      days = 7
    }
  }

  network_rules {
    default_action = "${usePrivateEndpoint ? 'Deny' : 'Allow'}"
    bypass         = ["AzureServices"]
  }

  tags = local.tags
}
${containerBlocks}
${peBlock}
`;
}
