import { AppInsightsConfig, Resource } from '../../types/resources';

export function generateAppInsightsModule(resource: Resource): string {
  const config = resource.config as AppInsightsConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();

  return `// modules/appInsights-${safeName}.bicep
// Generated by InfraHelper

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

@description('Application Insights kind')
param appInsightsKind string = '${config.kind}'

@description('Data retention in days (30-730)')
@minValue(30)
@maxValue(730)
param retentionDays int = ${config.retentionDays}

var workspaceName = '\${projectName}-\${environment}-law-${safeName}'
var appInsightsName = '\${projectName}-\${environment}-ai-${safeName}'

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

resource logAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: workspaceName
  location: location
  tags: tags
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: retentionDays
    features: {
      enableLogAccessUsingOnlyResourcePermissions: true
    }
    workspaceCapping: {
      dailyQuotaGb: -1
    }
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  tags: tags
  kind: appInsightsKind
  properties: {
    Application_Type: appInsightsKind
    WorkspaceResourceId: logAnalyticsWorkspace.id
    RetentionInDays: retentionDays
    IngestionMode: 'LogAnalytics'
    publicNetworkAccessForIngestion: 'Enabled'
    publicNetworkAccessForQuery: 'Enabled'
    DisableIpMasking: false
  }
}

output appInsightsId string = appInsights.id
output appInsightsName string = appInsights.name
output appInsightsInstrumentationKey string = appInsights.properties.InstrumentationKey
output appInsightsConnectionString string = appInsights.properties.ConnectionString
output logAnalyticsWorkspaceId string = logAnalyticsWorkspace.id
output logAnalyticsWorkspaceName string = logAnalyticsWorkspace.name
`;
}
