import { AppServiceConfig, Resource, ProjectConfig } from '../../types/resources';

function isLinuxFramework(framework: string): boolean {
  return framework === 'python' || framework === 'node';
}

function formatDotnetVersion(v: string): string {
  // '4.8' stays as-is, integers get '.0' suffix: '8' -> '8.0', '10' -> '10.0'
  return v.includes('.') ? v : `${v}.0`;
}

function getWindowsSiteConfig(framework: string, frameworkVersion: string): string {
  switch (framework) {
    case 'dotnet':
      return `netFrameworkVersion: 'v${formatDotnetVersion(frameworkVersion)}'`;
    case 'java':
      return `javaVersion: '${frameworkVersion}'\n      javaContainer: 'JAVA'\n      javaContainerVersion: 'SE'`;
    case 'php':
      return `phpVersion: '${frameworkVersion}'`;
    default:
      return `netFrameworkVersion: 'v${formatDotnetVersion(frameworkVersion)}'`;
  }
}

export function generateAppServiceModule(resource: Resource, project: ProjectConfig): string {
  const config = resource.config as AppServiceConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();

  const isLinux = isLinuxFramework(config.framework);

  // Find the App Insights reference
  const appInsightsRef = config.appInsightsRef
    ? project.resources.find((r) => r.id === config.appInsightsRef)
    : null;

  const appInsightsParamComment = appInsightsRef
    ? `// References App Insights: ${appInsightsRef.name}`
    : '// No App Insights linked';

  const customEnvVars = config.envVars
    .map((ev) => {
      if (ev.isSecret) {
        return `    { name: '${ev.key}', value: '@Microsoft.KeyVault(SecretUri=\${keyVaultBaseUri}secrets/${ev.key}/)' }`;
      }
      return `    { name: '${ev.key}', value: '${ev.value}' }`;
    })
    .join('\n');

  const hasSecrets = config.envVars.some((ev) => ev.isSecret);

  const skuTierMap: Record<string, string> = {
    B1: 'Basic',
    B2: 'Basic',
    B3: 'Basic',
    S1: 'Standard',
    S2: 'Standard',
    S3: 'Standard',
    P1v3: 'PremiumV3',
    P2v3: 'PremiumV3',
    P3v3: 'PremiumV3',
  };

  const skuTier = skuTierMap[config.sku] || 'Basic';

  return `// modules/appService-${safeName}.bicep
// Generated by InfraHelper

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

@description('App Service framework')
param framework string = '${config.framework}'

@description('Framework version')
param frameworkVersion string = '${config.frameworkVersion}'

@description('App Service Plan SKU (used only when creating a dedicated plan)')
param sku string = '${config.sku}'

@description('Resource ID of a shared App Service Plan. When set, no dedicated plan is created.')
param appServicePlanId string = ''

@description('Enable Always On')
param enableAlwaysOn bool = ${config.enableAlwaysOn}

${appInsightsParamComment}
param appInsightsConnectionString string = ''

@description('Subnet ID for VNet integration (leave empty to skip)')
param subnetId string = ''

@description('Subnet ID for private endpoint (leave empty to skip)')
param peSubnetId string = ''

@description('Private DNS Zone resource ID for web apps')
param privateDnsZoneWebId string = ''

@description('Additional app settings')
param additionalAppSettings array = []

@description('IP address to allow through access restrictions (empty = no restriction)')
param allowedIpAddress string = ''
${hasSecrets ? `\n@description('Key Vault base URI for secret references')\nparam keyVaultBaseUri string = ''` : ''}

var appServicePlanName = '\${projectName}-\${environment}-asp-${safeName}'
var appServiceName = '\${projectName}-\${environment}-app-${safeName}'

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

var baseAppSettings = [
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: appInsightsConnectionString }
  { name: 'ApplicationInsightsAgent_EXTENSION_VERSION', value: '~3' }
  { name: 'WEBSITE_RUN_FROM_PACKAGE', value: '1' }
]

var customAppSettings = [
${customEnvVars}
]

var allAppSettings = union(baseAppSettings, customAppSettings, additionalAppSettings)

resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = if (empty(appServicePlanId)) {
  name: appServicePlanName
  location: location
  tags: tags
  sku: {
    name: sku
    tier: '${skuTier}'
  }
  kind: ${isLinux ? "'linux'" : "'app'"}
  properties: {
    reserved: ${isLinux}
  }
}

var resolvedPlanId = empty(appServicePlanId) ? appServicePlan.id : appServicePlanId

resource appService 'Microsoft.Web/sites@2023-01-01' = {
  name: appServiceName
  location: location
  tags: tags
  kind: 'app'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: resolvedPlanId
    httpsOnly: true
    clientAffinityEnabled: false
    // Allow public access when IP restrictions are in use; otherwise lock down if private endpoint present
    publicNetworkAccess: !empty(allowedIpAddress) ? 'Enabled' : (!empty(peSubnetId) ? 'Disabled' : 'Enabled')
    virtualNetworkSubnetId: !empty(subnetId) ? subnetId : null
    siteConfig: {
      appSettings: allAppSettings
      alwaysOn: enableAlwaysOn
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      http20Enabled: true
      healthCheckPath: '/health'
      use32BitWorkerProcess: false
      ${isLinux ? `linuxFxVersion: '\${toUpper(framework)}|\${frameworkVersion}'` : getWindowsSiteConfig(config.framework, config.frameworkVersion)}
      ipSecurityRestrictions: !empty(allowedIpAddress) ? [
        {
          ipAddress: '\${allowedIpAddress}/32'
          action: 'Allow'
          priority: 100
          name: 'AllowDeploymentIP'
          description: 'Allow access from deployment machine'
        }
        {
          ipAddress: 'Any'
          action: 'Deny'
          priority: 2147483647
          name: 'DenyAll'
        }
      ] : []
    }
  }
}

// Auto-scaling for Premium tiers
resource autoScaleSettings 'Microsoft.Insights/autoscalesettings@2022-10-01' = if (startsWith(sku, 'P')) {
  name: '\${appServicePlanName}-autoscale'
  location: location
  tags: tags
  properties: {
    enabled: true
    targetResourceUri: appServicePlan.id
    profiles: [
      {
        name: 'Default'
        capacity: {
          minimum: '1'
          maximum: '5'
          default: '1'
        }
        rules: [
          {
            metricTrigger: {
              metricName: 'CpuPercentage'
              metricResourceUri: appServicePlan.id
              timeGrain: 'PT1M'
              statistic: 'Average'
              timeWindow: 'PT10M'
              timeAggregation: 'Average'
              operator: 'GreaterThan'
              threshold: 70
            }
            scaleAction: {
              direction: 'Increase'
              type: 'ChangeCount'
              value: '1'
              cooldown: 'PT5M'
            }
          }
          {
            metricTrigger: {
              metricName: 'CpuPercentage'
              metricResourceUri: appServicePlan.id
              timeGrain: 'PT1M'
              statistic: 'Average'
              timeWindow: 'PT10M'
              timeAggregation: 'Average'
              operator: 'LessThan'
              threshold: 30
            }
            scaleAction: {
              direction: 'Decrease'
              type: 'ChangeCount'
              value: '1'
              cooldown: 'PT5M'
            }
          }
        ]
      }
    ]
  }
}

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = if (!empty(peSubnetId)) {
  name: '\${appServiceName}-pe'
  location: location
  tags: tags
  properties: {
    subnet: {
      id: peSubnetId
    }
    privateLinkServiceConnections: [
      {
        name: '\${appServiceName}-pe-connection'
        properties: {
          privateLinkServiceId: appService.id
          groupIds: [
            'sites'
          ]
        }
      }
    ]
  }
}

resource privateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = if (!empty(peSubnetId) && !empty(privateDnsZoneWebId)) {
  parent: privateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-azurewebsites-net'
        properties: {
          privateDnsZoneId: privateDnsZoneWebId
        }
      }
    ]
  }
}

output appServiceId string = appService.id
output appServiceName string = appService.name
output appServiceHostname string = appService.properties.defaultHostName
output appServicePrincipalId string = appService.identity.principalId
output appServicePlanId string = resolvedPlanId
`;
}
