import { AppServicePlanConfig, Resource } from '../../types/resources';

const skuTierMap: Record<string, string> = {
  EP1: 'ElasticPremium',
  EP2: 'ElasticPremium',
  EP3: 'ElasticPremium',
  B1: 'Basic',
  B2: 'Basic',
  B3: 'Basic',
  S1: 'Standard',
  S2: 'Standard',
  S3: 'Standard',
  P1v3: 'PremiumV3',
  P2v3: 'PremiumV3',
  P3v3: 'PremiumV3',
};

export function generateAppServicePlanModule(resource: Resource): string {
  const config = resource.config as AppServicePlanConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();
  const isLinux = config.os === 'Linux';
  const skuTier = skuTierMap[config.sku] || 'Basic';

  return `// modules/appServicePlan-${safeName}.bicep
// Generated by InfraHelper — shared App Service Plan

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

var appServicePlanName = '\${projectName}-\${environment}-asp-${safeName}'

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {
  name: appServicePlanName
  location: location
  tags: tags
  sku: {
    name: '${config.sku}'
    tier: '${skuTier}'
  }
  kind: ${isLinux ? "'linux'" : "'app'"}
  properties: {
    reserved: ${isLinux}
  }
}

output appServicePlanId string = appServicePlan.id
output appServicePlanName string = appServicePlan.name
`;
}
