import { FunctionAppConfig, Resource, ProjectConfig } from '../../types/resources';

function getRuntimeSettings(runtime: string, runtimeVersion: string): string[] {
  const settings: string[] = [];
  switch (runtime) {
    case 'dotnet':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'dotnet' }`);
      break;
    case 'dotnet-isolated':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'dotnet-isolated' }`);
      settings.push(`      { name: 'WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED', value: '1' }`);
      break;
    case 'node':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'node' }`);
      settings.push(`      { name: 'WEBSITE_NODE_DEFAULT_VERSION', value: '~${runtimeVersion}' }`);
      break;
    case 'python':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'python' }`);
      break;
    case 'java':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'java' }`);
      break;
    case 'powershell':
      settings.push(`      { name: 'FUNCTIONS_WORKER_RUNTIME', value: 'powershell' }`);
      break;
  }
  return settings;
}

export function generateFunctionAppModule(resource: Resource, project: ProjectConfig): string {
  const config = resource.config as FunctionAppConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();

  // Python always requires Linux; otherwise respect the configured OS
  const isLinux = config.runtime === 'python' || config.os === 'Linux';

  const runtimeSettings = getRuntimeSettings(config.runtime, config.runtimeVersion);

  // Find the storage account reference
  const storageRef = config.storageAccountRef
    ? project.resources.find((r) => r.id === config.storageAccountRef)
    : null;
  const appInsightsRef = config.appInsightsRef
    ? project.resources.find((r) => r.id === config.appInsightsRef)
    : null;

  const storageParamComment = storageRef
    ? `// References storage account: ${storageRef.name}`
    : '// No storage account linked - provide connection string';

  const appInsightsParamComment = appInsightsRef
    ? `// References App Insights: ${appInsightsRef.name}`
    : '// No App Insights linked';

  // Build custom env vars
  const customEnvVars = config.envVars
    .map((ev) => {
      if (ev.isSecret) {
        return `      { name: '${ev.key}', value: '@Microsoft.KeyVault(SecretUri=\${keyVaultBaseUri}secrets/${ev.key}/)' }`;
      }
      return `      { name: '${ev.key}', value: '${ev.value}' }`;
    })
    .join('\n');

  const hasSecrets = config.envVars.some((ev) => ev.isSecret);

  return `// modules/functionApp-${safeName}.bicep
// Generated by InfraHelper

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

@description('Function App runtime')
param runtime string = '${config.runtime}'

@description('Function App runtime version')
param runtimeVersion string = '${config.runtimeVersion}'

@description('App Service Plan SKU (used only when creating a dedicated plan)')
param sku string = '${config.sku}'

@description('Resource ID of a shared App Service Plan. When set, no dedicated plan is created.')
param appServicePlanId string = ''

${storageParamComment}
param storageAccountConnectionString string

${appInsightsParamComment}
param appInsightsConnectionString string = ''

@description('Subnet ID for VNet integration (leave empty to skip)')
param subnetId string = ''

@description('Subnet ID for private endpoint (leave empty to skip)')
param peSubnetId string = ''

@description('Private DNS Zone resource ID for web apps')
param privateDnsZoneWebId string = ''

@description('Additional app settings')
param additionalAppSettings array = []

@description('IP address to allow through access restrictions (empty = no restriction)')
param allowedIpAddress string = ''
${hasSecrets ? `\n@description('Key Vault base URI for secret references')\nparam keyVaultBaseUri string = ''` : ''}

var appServicePlanName = '\${projectName}-\${environment}-asp-func-${safeName}'
var functionAppName = '\${projectName}-\${environment}-func-${safeName}'

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

var baseAppSettings = [
  { name: 'AzureWebJobsStorage', value: storageAccountConnectionString }
  { name: 'FUNCTIONS_EXTENSION_VERSION', value: '~4' }
${runtimeSettings.join('\n')}
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: appInsightsConnectionString }
]

// WEBSITE_CONTENT* settings are required for Consumption (Y1) plans only.
// Including them on Elastic Premium (EP*) plans breaks deployment.
var consumptionOnlySettings = sku == 'Y1' ? [
  { name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING', value: storageAccountConnectionString }
  { name: 'WEBSITE_CONTENTSHARE', value: toLower(functionAppName) }
] : []

var customAppSettings = [
${customEnvVars}
]

var allAppSettings = union(baseAppSettings, consumptionOnlySettings, customAppSettings, additionalAppSettings)

resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = if (empty(appServicePlanId)) {
  name: appServicePlanName
  location: location
  tags: tags
  sku: {
    name: sku
  }
  kind: ${isLinux ? "'linux'" : "'windows'"}
  properties: {
    reserved: ${isLinux}
  }
}

var resolvedPlanId = empty(appServicePlanId) ? appServicePlan.id : appServicePlanId

resource functionApp 'Microsoft.Web/sites@2023-01-01' = {
  name: functionAppName
  location: location
  tags: tags
  kind: ${isLinux ? "'functionapp,linux'" : "'functionapp'"}
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: resolvedPlanId
    httpsOnly: true
    clientAffinityEnabled: false
    // Allow public access when IP restrictions are in use; otherwise lock down if private endpoint present
    publicNetworkAccess: !empty(allowedIpAddress) ? 'Enabled' : (!empty(peSubnetId) ? 'Disabled' : 'Enabled')
    virtualNetworkSubnetId: !empty(subnetId) ? subnetId : null
    siteConfig: {
      appSettings: allAppSettings
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      http20Enabled: true
      ${isLinux ? `linuxFxVersion: '\${toUpper(runtime)}|\${runtimeVersion}.0'` : ''}
      use32BitWorkerProcess: false
      alwaysOn: sku != 'Y1'
      ipSecurityRestrictions: !empty(allowedIpAddress) ? [
        {
          ipAddress: '\${allowedIpAddress}/32'
          action: 'Allow'
          priority: 100
          name: 'AllowDeploymentIP'
          description: 'Allow access from deployment machine'
        }
        {
          ipAddress: 'Any'
          action: 'Deny'
          priority: 2147483647
          name: 'DenyAll'
        }
      ] : []
    }
  }
}

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = if (!empty(peSubnetId)) {
  name: '\${functionAppName}-pe'
  location: location
  tags: tags
  properties: {
    subnet: {
      id: peSubnetId
    }
    privateLinkServiceConnections: [
      {
        name: '\${functionAppName}-pe-connection'
        properties: {
          privateLinkServiceId: functionApp.id
          groupIds: [
            'sites'
          ]
        }
      }
    ]
  }
}

resource privateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = if (!empty(peSubnetId) && !empty(privateDnsZoneWebId)) {
  parent: privateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-azurewebsites-net'
        properties: {
          privateDnsZoneId: privateDnsZoneWebId
        }
      }
    ]
  }
}

output functionAppId string = functionApp.id
output functionAppName string = functionApp.name
output functionAppHostname string = functionApp.properties.defaultHostName
output functionAppPrincipalId string = functionApp.identity.principalId
output appServicePlanId string = resolvedPlanId
`;
}
