import { KeyVaultConfig, Resource } from '../../types/resources';

export function generateKeyVaultModule(resource: Resource): string {
  const config = resource.config as KeyVaultConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();

  return `// modules/keyVault-${safeName}.bicep
// Generated by InfraHelper

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

@description('Key Vault SKU')
param kvSku string = '${config.sku}'

@description('Enable soft delete')
param enableSoftDelete bool = ${config.enableSoftDelete}

@description('Soft delete retention days')
@minValue(7)
@maxValue(90)
param softDeleteRetentionDays int = ${config.softDeleteRetentionDays}

@description('Subnet ID for private endpoint (leave empty to skip)')
param subnetId string = ''

@description('Private DNS Zone resource ID for Key Vault')
param privateDnsZoneKeyVaultId string = ''

@description('Tenant ID for the Key Vault')
param tenantId string = subscription().tenantId

var keyVaultName = '\${projectName}-\${environment}-kv-${safeName}'
// Key Vault names must be 3-24 chars
var kvName = length(keyVaultName) > 24 ? substring(keyVaultName, 0, 24) : keyVaultName

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: kvName
  location: location
  tags: tags
  properties: {
    tenantId: tenantId
    sku: {
      family: 'A'
      name: kvSku
    }
    enableRbacAuthorization: true
    enableSoftDelete: enableSoftDelete
    softDeleteRetentionInDays: softDeleteRetentionDays
    enabledForDeployment: false
    enabledForDiskEncryption: false
    enabledForTemplateDeployment: true
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: empty(subnetId) ? 'Allow' : 'Deny'
      ipRules: []
      virtualNetworkRules: []
    }
    publicNetworkAccess: empty(subnetId) ? 'Enabled' : 'Disabled'
  }
}

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = if (!empty(subnetId)) {
  name: '\${kvName}-pe'
  location: location
  tags: tags
  properties: {
    subnet: {
      id: subnetId
    }
    privateLinkServiceConnections: [
      {
        name: '\${kvName}-pe-connection'
        properties: {
          privateLinkServiceId: keyVault.id
          groupIds: [
            'vault'
          ]
        }
      }
    ]
  }
}

resource privateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = if (!empty(subnetId) && !empty(privateDnsZoneKeyVaultId)) {
  parent: privateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-vaultcore-azure-net'
        properties: {
          privateDnsZoneId: privateDnsZoneKeyVaultId
        }
      }
    ]
  }
}

// Diagnostic settings for audit logging
resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: '\${kvName}-diag'
  scope: keyVault
  properties: {
    logs: [
      {
        category: 'AuditEvent'
        enabled: true
      }
      {
        category: 'AzurePolicyEvaluationDetails'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
  }
}

output keyVaultId string = keyVault.id
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
`;
}
