import { StorageAccountConfig, Resource } from '../../types/resources';

export function generateStorageModule(resource: Resource): string {
  const config = resource.config as StorageAccountConfig;
  const safeName = resource.name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

  const containerResources = config.containers
    .map(
      (c) => `
resource blobContainer${c.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-01-01' = {
  parent: blobService
  name: '${c}'
  properties: {
    publicAccess: enableBlobPublicAccess ? 'Blob' : 'None'
  }
}`
    )
    .join('\n');

  return `// modules/storageAccount-${safeName}.bicep
// Generated by InfraHelper

@description('Project name prefix for all resources')
param projectName string

@description('Environment name')
param environment string

@description('Azure region for deployment')
param location string = resourceGroup().location

@description('Storage account SKU')
param sku string = '${config.sku}'

@description('Storage account kind')
param storageKind string = '${config.kind}'

@description('Enable blob public access')
param enableBlobPublicAccess bool = ${config.enableBlobPublicAccess}

@description('Subnet ID for private endpoint (leave empty to skip)')
param subnetId string = ''

@description('Private DNS Zone resource ID for blob storage')
param privateDnsZoneBlobId string = ''

// Storage account names must be 3-24 chars, lowercase alphanumeric only
var saName = length('${safeName}') > 24 ? substring('${safeName}', 0, 24) : '${safeName}'

var tags = {
  environment: environment
  project: projectName
  managedBy: 'InfraHelper'
  resourceName: '${resource.name}'
}

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: saName
  location: location
  tags: tags
  sku: {
    name: sku
  }
  kind: storageKind
  properties: {
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: enableBlobPublicAccess
    allowSharedKeyAccess: true
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: empty(subnetId) ? 'Allow' : 'Deny'
    }
    encryption: {
      services: {
        blob: {
          enabled: true
          keyType: 'Account'
        }
        file: {
          enabled: true
          keyType: 'Account'
        }
      }
      keySource: 'Microsoft.Storage'
    }
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-01-01' = {
  parent: storageAccount
  name: 'default'
  properties: {
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}
${containerResources}
resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = if (!empty(subnetId)) {
  name: '\${saName}-pe'
  location: location
  tags: tags
  properties: {
    subnet: {
      id: subnetId
    }
    privateLinkServiceConnections: [
      {
        name: '\${saName}-pe-connection'
        properties: {
          privateLinkServiceId: storageAccount.id
          groupIds: [
            'blob'
          ]
        }
      }
    ]
  }
}

resource privateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = if (!empty(subnetId) && !empty(privateDnsZoneBlobId)) {
  parent: privateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-blob-core-windows-net'
        properties: {
          privateDnsZoneId: privateDnsZoneBlobId
        }
      }
    ]
  }
}

output storageAccountId string = storageAccount.id
output storageAccountName string = storageAccount.name
output storageAccountPrimaryEndpoint string = storageAccount.properties.primaryEndpoints.blob
output storageAccountConnectionString string = 'DefaultEndpointsProtocol=https;AccountName=\${storageAccount.name};AccountKey=\${storageAccount.listKeys().keys[0].value};EndpointSuffix=core.windows.net'
`;
}
